version: '4.3.0'

services:

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TrainStation
      MYSQL_USER: trainStation
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'